name: "\U0001F41B Bug Report"
description: Spotted a bug? Add a report to help us improve this template
title: "\U0001F41B Bug - "
labels: 
  - bug
  - needs triage
body:
  - type: markdown
    attributes:
      value: |
        # Bug report

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Please provide us with a brief summary of the bug, a few words will do. Providing screenshots is encouraged
      placeholder: Brief summary of the bug
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Which browser/operating system did you encounter this bug in?
      placeholder: Browser/Operating System
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide us the steps for how to reproduce this bug
      placeholder: Steps to reproduce the bug
      required: true

  - type: textarea
    id: expected_results
    attributes:
      label: Expected results
      description: What did you expect to experience?
      placeholder: Expected results
      required: true

  - type: textarea
    id: actual_results
    attributes:
      label: Actual results
      description: What did you experience instead of the above?
      placeholder: Actual results
      required: true
