name: "\U0001F4AC Give feedback on a component"
description: Give us feedback to help us improve this template
title: "\U0001F4AC Feedback - "
labels: 
  - needs triage
body:
  - type: markdown
    attributes:
      value: |
        # Template feedback

  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Please provide us with your feedback on the template
      placeholder: Your feedback
      required: true
