name: '\U0001F4A1 Task'
description: Internal Task Template
title: '\U0001F4A1 Task - '
labels: 
  - needs review
  - needs triage
  - task
body:
  - type: markdown
    attributes:
      value: |
        # Task Description

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: Describe the current situation and why it needs to be addressed
      placeholder: Problem statement

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Outline your proposed approach to solving the problem
      placeholder: Proposed solution

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: List specific, measurable outcomes that define when this task is complete
      placeholder: Acceptance criteria

  - type: checkboxes
    id: task_size_estimation
    attributes:
      label: Task Size Estimation
      description: Select the appropriate size below
      options:
        - label: Small (1-2 hours)
          value: small
        - label: Medium (2-4 hours)
          value: medium
        - label: Large (4-8 hours)
          value: large
        - label: Extra Large (8+ hours)
          value: extra_large

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies or blockers
      placeholder: Dependencies

  - type: textarea
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Document any breaking changes this task might introduce
      placeholder: Breaking changes

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other relevant information
      placeholder: Additional notes
