name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Debug - Check Environment Variables
        run: |
          echo "Checking if env vars are set (not showing actual values)"
          if [ -n "$CONTENTFUL_SPACE_ID" ]; then echo "CONTENTFUL_SPACE_ID is set"; else echo "CONTENTFUL_SPACE_ID is NOT set"; fi
          if [ -n "$CONTENTFUL_ACCESS_TOKEN" ]; then echo "CONTENTFUL_ACCESS_TOKEN is set"; else echo "CONTENTFUL_ACCESS_TOKEN is NOT set"; fi
          if [ -n "$CONTENTFUL_PREVIEW_ACCESS_TOKEN" ]; then echo "CONTENTFUL_PREVIEW_ACCESS_TOKEN is set"; else echo "CONTENTFUL_PREVIEW_ACCESS_TOKEN is NOT set"; fi

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        env:
          NODE_ENV: test
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
        run: bunx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
